'use client';

import { useState } from 'react';
import * as XLSX from 'xlsx';
import { PageHeader } from '@/components/page-header';
import { FileSpreadsheet, Upload, CheckCircle2, Database, ShieldCheck } from 'lucide-react';

type Row = Record<string, string | number | boolean | null>;
const recommended=[
 ['transaction_id','Identifiant unique / anti-doublon'],['date','Date de transaction'],['value_date','Date de valeur'],['description','Libellé / description'],['amount','Montant'],['currency','Devise'],['type','income / expense / transfer'],['category','Catégorie principale'],['subcategory','Sous-catégorie'],['account','Compte'],['counterparty','Bénéficiaire / commerçant'],['payment_method','Espèces, carte, virement, mobile money'],['reference','Référence transaction'],['project','Projet lié'],['budget_period','Semaine / mois budgétaire'],['planned_or_actual','Prévue ou réelle'],['status','planned / pending / cleared / cancelled'],['recurrence','Récurrence'],['quantity','Quantité'],['unit_price','Prix unitaire'],['fees','Frais'],['tax','Taxes'],['tags','Tags'],['location','Lieu'],['notes','Notes'],['source','Source de donnée'],['imported_at','Date d’import'],['confidence','Niveau de confiance']
];
export default function ImportPage(){
  const [rows,setRows]=useState<Row[]>([]);const [name,setName]=useState('');const [validated,setValidated]=useState(false);
  async function readFile(file: File){setName(file.name);const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:'array',cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];const json=XLSX.utils.sheet_to_json<Row>(ws,{defval:''});setRows(json.slice(0,250));}
  const keys=rows[0]?Object.keys(rows[0]):[];
  function validateImport(){const batch={id:Date.now(),file:name,rows:rows.length,columns:keys,validatedAt:new Date().toISOString()};const list=JSON.parse(localStorage.getItem('finpilot-imports')||'[]');localStorage.setItem('finpilot-imports',JSON.stringify([batch,...list]));setValidated(true);const notices=JSON.parse(localStorage.getItem('finpilot-notifications')||'[]');notices.unshift({id:'import-'+batch.id,title:'Import validé',body:`${name} — ${rows.length} lignes prêtes`,time:'Maintenant'});localStorage.setItem('finpilot-notifications',JSON.stringify(notices));}
  return <>
    <PageHeader eyebrow="Data intake" title="Importer un fichier Excel" subtitle="Import avancé avec mapping de données financières, contrôle des doublons, prévisualisation et préparation à l’historisation."/>
    <div className="grid-2 import-top-grid"><div className="card"><label className="upload-zone" style={{display:'block',cursor:'pointer'}}><FileSpreadsheet size={34} style={{margin:'0 auto 12px'}}/><div style={{fontWeight:800}}>Déposez votre fichier .xlsx / .xls / .csv</div><div className="section-caption" style={{margin:'7px 0 16px'}}>Prévisualisation locale avant validation.</div><span className="btn btn-primary"><Upload size={16}/>Choisir un fichier</span><input type="file" accept=".xlsx,.xls,.csv" style={{display:'none'}} onChange={e=>e.target.files?.[0]&&readFile(e.target.files[0])}/></label>{name&&<div className="kpi-row"><span><CheckCircle2 size={15} style={{display:'inline',marginRight:7}}/>{name}</span><strong>{rows.length} lignes prévisualisées</strong></div>}</div>
    <div className="card"><div className="section-head"><div><div className="section-title">Colonnes capitales recommandées</div><div className="section-caption">Le mapping peut accepter des noms différents.</div></div><Database size={20}/></div><div className="recommended-columns">{recommended.map(([key,label])=><div className="recommended-column" key={key}><code>{key}</code><span>{label}</span></div>)}</div></div></div>
    <div className="section grid-3 import-checks"><div className="card"><ShieldCheck size={20}/><strong>Contrôle doublons</strong><span>Utilisez transaction_id + date + montant + compte.</span></div><div className="card"><ShieldCheck size={20}/><strong>Validation métier</strong><span>Montants, devises, dates, catégories et statuts contrôlés.</span></div><div className="card"><ShieldCheck size={20}/><strong>Traçabilité</strong><span>Source, import_batch et date d’import conservables.</span></div></div>
    {rows.length>0&&<div className="section card"><div className="section-head"><div><div className="section-title">Aperçu avant import</div><div className="section-caption">Affichage horizontal de toutes les colonnes détectées. Jusqu’à 250 lignes en prévisualisation.</div></div><button className="btn btn-primary" onClick={validateImport}>{validated?'Mapping validé ✓':'Valider le mapping'}</button></div><div className="table-wrap wide-preview"><table><thead><tr>{keys.map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.slice(0,15).map((r,i)=><tr key={i}>{keys.map(k=><td key={k}>{String(r[k]??'')}</td>)}</tr>)}</tbody></table></div></div>}
  </>;
}
