'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Plus, Pencil, Trash2, Download, Archive, Sparkles, X } from 'lucide-react';

type Budget={id:number;name:string;limit:number;spent:number;period:string};
type Hist={id:number;name:string;limit:number;spent:number;period:string;archivedAt:string};
const money=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export function BudgetManager(){
 const [monthly,setMonthly]=useState(2400);const [savings,setSavings]=useState(500);const [period,setPeriod]=useState('2026-09');
 const [budgets,setBudgets]=useState<Budget[]>([{id:1,name:'Logement',limit:900,spent:780,period},{id:2,name:'Transport',limit:400,spent:245,period},{id:3,name:'Santé',limit:300,spent:110,period},{id:4,name:'Alimentation',limit:500,spent:405,period}]);
 const [history,setHistory]=useState<Hist[]>([]);const [open,setOpen]=useState(false);const [editId,setEditId]=useState<number|null>(null);const [draft,setDraft]=useState({name:'',limit:0,spent:0});
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('finpilot-budgets')||'null');if(s){setMonthly(s.monthly??2400);setSavings(s.savings??500);setBudgets(s.budgets??[]);setHistory(s.history??[]);setPeriod(s.period??'2026-09')}}catch{}},[]);
 useEffect(()=>{localStorage.setItem('finpilot-budgets',JSON.stringify({monthly,savings,budgets,history,period}))},[monthly,savings,budgets,history,period]);
 const spent=useMemo(()=>budgets.reduce((s,b)=>s+b.spent,0),[budgets]);const remaining=monthly-spent;
 function newBudget(){setEditId(null);setDraft({name:'',limit:0,spent:0});setOpen(true)}
 function edit(b:Budget){setEditId(b.id);setDraft({name:b.name,limit:b.limit,spent:b.spent});setOpen(true)}
 function save(e:React.FormEvent){e.preventDefault();if(!draft.name.trim())return;if(editId)setBudgets(x=>x.map(b=>b.id===editId?{...b,...draft}:b));else setBudgets(x=>[...x,{id:Date.now(),period,...draft}]);setOpen(false)}
 function archive(b:Budget){setHistory(h=>[{id:Date.now(),name:b.name,limit:b.limit,spent:b.spent,period:b.period,archivedAt:new Date().toISOString()},...h])}
 function closePeriod(){const items=budgets.map((b,i)=>({id:Date.now()+i,name:b.name,limit:b.limit,spent:b.spent,period,archivedAt:new Date().toISOString()}));setHistory(h=>[...items,...h]);setBudgets(x=>x.map(b=>({...b,spent:0,period})));}
 function exportCsv(){const csv=['Categorie,Periode,Budget,Depense,Ecart,Archive le',...history.map(h=>[h.name,h.period,h.limit,h.spent,h.limit-h.spent,h.archivedAt].join(','))].join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=u;a.download='finpilot-budget-history.csv';a.click();URL.revokeObjectURL(u)}
 return <>
  <div className="topbar"><div><div className="eyebrow">Budget & Spending</div><h1>Budget mensuel</h1><div className="subtitle">Modifiez vos objectifs, catégories et dépenses réelles. Chaque période peut être clôturée et historisée.</div></div><div className="actions"><Link className="btn" href="/forecast"><Sparkles size={16}/>Prévoir par %</Link><button className="btn" onClick={closePeriod}><Archive size={16}/>Clôturer la période</button><button className="btn btn-primary" onClick={newBudget}><Plus size={16}/>Nouveau budget</button></div></div>
  <div className="grid-4 editable-metrics">
   <div className="card metric-card"><div className="metric-label">Budget mensuel</div><input className="metric-input" type="number" value={monthly||''} onChange={e=>setMonthly(e.target.value===''?0:Number(e.target.value))}/><div className="delta">Montant modifiable</div></div>
   <div className="card metric-card"><div className="metric-label">Dépenses réelles</div><div className="metric">{money(spent)}</div><div className="delta neg">{monthly?Math.round(spent/monthly*100):0}% du budget</div></div>
   <div className="card metric-card"><div className="metric-label">Reste disponible</div><div className="metric">{money(remaining)}</div><div className="delta">{monthly?Math.round(remaining/monthly*100):0}% restant</div></div>
   <div className="card metric-card"><div className="metric-label">Épargne cible</div><input className="metric-input" type="number" value={savings||''} onChange={e=>setSavings(e.target.value===''?0:Number(e.target.value))}/><div className="delta">{monthly?Math.round(savings/monthly*100):0}% du budget</div></div>
  </div>
  <div className="section card"><div className="section-head"><div><div className="section-title">Budgets par catégorie</div><div className="section-caption">Ajouter, modifier, supprimer ou historiser chaque poste.</div></div><div className="field compact-field"><label>Période</label><input className="input" type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></div></div>
   <div className="budget-grid">{budgets.map(b=>{const pct=b.limit?Math.round(b.spent/b.limit*100):0;return <div className="budget-card" key={b.id}><div className="budget-card-head"><div><strong>{b.name}</strong><span>{money(b.spent)} sur {money(b.limit)}</span></div><div className="row-actions"><button className="icon-btn subtle" onClick={()=>edit(b)}><Pencil size={15}/></button><button className="icon-btn subtle" onClick={()=>archive(b)}><Archive size={15}/></button><button className="icon-btn subtle" onClick={()=>setBudgets(x=>x.filter(v=>v.id!==b.id))}><Trash2 size={15}/></button></div></div><div className="progress"><span style={{width:`${Math.min(pct,100)}%`}}/></div><div className="budget-footer"><span>{pct}% utilisé</span><b>{money(b.limit-b.spent)} restant</b></div></div>})}</div>
  </div>
  <div className="section card"><div className="section-head"><div><div className="section-title">Historique des budgets</div><div className="section-caption">Périodes clôturées ou éléments archivés.</div></div><button className="btn" onClick={exportCsv}><Download size={16}/>Exporter CSV</button></div><div className="table-wrap"><table><thead><tr><th>Période</th><th>Catégorie</th><th>Budget</th><th>Dépensé</th><th>Écart</th></tr></thead><tbody>{history.length?history.map(h=><tr key={h.id}><td>{h.period}</td><td><strong>{h.name}</strong></td><td>{money(h.limit)}</td><td>{money(h.spent)}</td><td>{money(h.limit-h.spent)}</td></tr>):<tr><td colSpan={5} className="empty-cell">Aucune période clôturée.</td></tr>}</tbody></table></div></div>
  {open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><form className="modal-card" onMouseDown={e=>e.stopPropagation()} onSubmit={save}><div className="modal-head"><div className="section-title">{editId?'Modifier le budget':'Nouveau budget'}</div><button type="button" className="icon-btn" onClick={()=>setOpen(false)}><X size={17}/></button></div><div className="field"><label>Catégorie</label><input className="input" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} required/></div><div className="field"><label>Budget prévu</label><input className="input" type="number" value={draft.limit||''} onChange={e=>setDraft({...draft,limit:e.target.value===''?0:Number(e.target.value)})}/></div><div className="field"><label>Dépenses réalisées</label><input className="input" type="number" value={draft.spent||''} onChange={e=>setDraft({...draft,spent:e.target.value===''?0:Number(e.target.value)})}/></div><div className="recurrence-actions"><button className="btn btn-primary">Enregistrer</button><button type="button" className="btn" onClick={()=>setOpen(false)}>Annuler</button></div></form></div>}
 </>
}
