'use client';

import { useEffect, useMemo, useState } from 'react';
import { Plus, Pencil, Trash2, WalletCards, ArrowDownLeft, ArrowUpRight, CheckCircle2, X, CalendarDays, Download } from 'lucide-react';

type Obligation={id:number;direction:'payable'|'receivable';counterparty:string;label:string;amount:number;paid:number;due:string;status:'Ouverte'|'Partielle'|'Réglée';notes:string};
const money=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'USD'}).format(n||0);
const empty:Omit<Obligation,'id'>={direction:'payable',counterparty:'',label:'',amount:0,paid:0,due:new Date().toISOString().slice(0,10),status:'Ouverte',notes:''};

export function DebtManager(){
 const [items,setItems]=useState<Obligation[]>([]); const [open,setOpen]=useState(false); const [editId,setEditId]=useState<number|null>(null); const [draft,setDraft]=useState(empty);
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('finpilot-debts')||'null');if(s)setItems(s);else setItems([{id:1,direction:'payable',counterparty:'Marc',label:'Prêt personnel',amount:400,paid:100,due:'2026-10-15',status:'Partielle',notes:'Remboursement en 2 tranches'},{id:2,direction:'receivable',counterparty:'Client Studio',label:'Solde shooting',amount:650,paid:0,due:'2026-10-04',status:'Ouverte',notes:'À encaisser après livraison'}])}catch{}},[]);
 useEffect(()=>{if(items.length)localStorage.setItem('finpilot-debts',JSON.stringify(items))},[items]);
 const payable=useMemo(()=>items.filter(x=>x.direction==='payable').reduce((s,x)=>s+Math.max(0,x.amount-x.paid),0),[items]);
 const receivable=useMemo(()=>items.filter(x=>x.direction==='receivable').reduce((s,x)=>s+Math.max(0,x.amount-x.paid),0),[items]);
 function start(direction:'payable'|'receivable'='payable'){setEditId(null);setDraft({...empty,direction});setOpen(true)}
 function edit(x:Obligation){setEditId(x.id);setDraft({...x});setOpen(true)}
 function save(e:React.FormEvent){e.preventDefault();const status=draft.paid<=0?'Ouverte':draft.paid>=draft.amount?'Réglée':'Partielle';const item={...draft,status} as Omit<Obligation,'id'>;setItems(x=>editId?x.map(v=>v.id===editId?{id:editId,...item}:v):[{id:Date.now(),...item},...x]);setOpen(false)}
 function settle(x:Obligation){setItems(list=>list.map(v=>v.id===x.id?{...v,paid:v.amount,status:'Réglée'}:v));const notices=JSON.parse(localStorage.getItem('finpilot-notifications')||'[]');notices.unshift({id:'debt-'+Date.now(),title:x.direction==='payable'?'Dette réglée':'Créance encaissée',body:`${x.label} — ${money(x.amount)}`,time:'Maintenant'});localStorage.setItem('finpilot-notifications',JSON.stringify(notices));}
 function exportCsv(){const csv=['Type,Contrepartie,Objet,Montant,Paye,Reste,Echeance,Statut,Notes',...items.map(x=>[x.direction,x.counterparty,x.label,x.amount,x.paid,Math.max(0,x.amount-x.paid),x.due,x.status,x.notes].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))].join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=u;a.download='finpilot-dettes-creances.csv';a.click();URL.revokeObjectURL(u)}
 return <>
  <div className="topbar"><div><div className="eyebrow">Dettes & créances</div><h1>Ce que je dois / ce qu’on me doit</h1><div className="subtitle">Les dettes à payer diminuent votre position nette. Les créances à recevoir alimentent les revenus prévisionnels jusqu’à encaissement.</div></div><div className="actions"><button className="btn" onClick={exportCsv}><Download size={16}/>Exporter</button><button className="btn" onClick={()=>start('receivable')}><ArrowDownLeft size={16}/>Argent à recevoir</button><button className="btn btn-primary" onClick={()=>start('payable')}><Plus size={16}/>Nouvelle dette</button></div></div>
  <div className="grid-3"><div className="card"><div className="metric-label">Dettes restantes</div><div className="metric text-negative">-{money(payable)}</div><div className="section-caption">Impact négatif sur la position nette</div></div><div className="card"><div className="metric-label">Créances à recevoir</div><div className="metric positive">+{money(receivable)}</div><div className="section-caption">Revenus futurs non encore encaissés</div></div><div className="card"><div className="metric-label">Position nette obligations</div><div className={`metric ${receivable-payable<0?'text-negative':'positive'}`}>{money(receivable-payable)}</div><div className="section-caption">Créances - dettes</div></div></div>
  <div className="section card"><div className="table-wrap"><table><thead><tr><th>Type</th><th>Contrepartie</th><th>Objet</th><th>Échéance</th><th>Total</th><th>Payé/encaissé</th><th>Reste</th><th>Statut</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><span className={`pill ${x.direction==='receivable'?'green':'red'}`}>{x.direction==='receivable'?'À recevoir':'À payer'}</span></td><td>{x.counterparty}</td><td><strong>{x.label}</strong></td><td>{new Date(x.due+'T00:00:00').toLocaleDateString('fr-FR')}</td><td>{money(x.amount)}</td><td>{money(x.paid)}</td><td className={x.direction==='payable'?'negative':'positive'}>{money(Math.max(0,x.amount-x.paid))}</td><td>{x.status}</td><td><div className="row-actions"><button className="icon-btn subtle" onClick={()=>edit(x)} title="Modifier"><Pencil size={15}/></button>{x.status!=='Réglée'&&<button className="icon-btn subtle" onClick={()=>settle(x)} title={x.direction==='payable'?'Marquer payé':'Marquer encaissé'}><CheckCircle2 size={15}/></button>}<button className="icon-btn subtle" onClick={()=>setItems(v=>v.filter(a=>a.id!==x.id))} title="Supprimer"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div></div>
  {open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><form className="modal-card transaction-form" onMouseDown={e=>e.stopPropagation()} onSubmit={save}><div className="modal-head"><div><div className="section-title">{editId?'Modifier':'Ajouter'} une obligation</div><div className="section-caption">Une dette n’est une dépense réelle qu’au paiement; une créance n’est un revenu réel qu’à l’encaissement.</div></div><button type="button" className="icon-btn" onClick={()=>setOpen(false)}><X size={17}/></button></div><div className="field"><label>Type</label><select className="select" value={draft.direction} onChange={e=>setDraft({...draft,direction:e.target.value as 'payable'|'receivable'})}><option value="payable">Je dois de l’argent</option><option value="receivable">On me doit de l’argent</option></select></div><div className="field"><label>Personne / entreprise</label><input className="input" required value={draft.counterparty} onChange={e=>setDraft({...draft,counterparty:e.target.value})}/></div><div className="field"><label>Objet</label><input className="input" required value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}/></div><div className="field"><label>Montant total</label><input className="input" type="number" min="0" step="0.01" value={draft.amount||''} onChange={e=>setDraft({...draft,amount:e.target.value===''?0:Number(e.target.value)})}/></div><div className="field"><label>Déjà payé / encaissé</label><input className="input" type="number" min="0" step="0.01" value={draft.paid||''} onChange={e=>setDraft({...draft,paid:e.target.value===''?0:Number(e.target.value)})}/></div><div className="field"><label>Échéance</label><input className="input" type="date" value={draft.due} onChange={e=>setDraft({...draft,due:e.target.value})}/></div><div className="field field-wide"><label>Notes</label><textarea className="input textarea" value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></div><div className="recurrence-actions"><button className="btn btn-primary" type="submit"><WalletCards size={15}/>Enregistrer</button><button className="btn" type="button" onClick={()=>setOpen(false)}>Annuler</button></div></form></div>}
 </>
}
