'use client';
import { useEffect, useMemo, useState } from 'react';
import { Filter, Plus, Pencil, Trash2, X, Search, CalendarDays, WalletCards, Tag } from 'lucide-react';

type Tx={id:number;date:string;label:string;category:string;type:string;status:string;amount:number;account:string;method:string;reference:string;notes:string};
const seed:Tx[]=[{id:1,date:'2026-09-18',label:'Loyer mensuel',category:'Logement',type:'Dépense réelle',status:'Payé',amount:1150,account:'Compte principal',method:'Virement',reference:'LOY-SEP-26',notes:'Loyer septembre'},{id:2,date:'2026-09-14',label:'Courses',category:'Alimentation',type:'Dépense réelle',status:'Payé',amount:148,account:'Cash',method:'Espèces',reference:'',notes:''},{id:3,date:'2026-09-12',label:'Assurance santé',category:'Assurance',type:'Dépense réelle',status:'Payé',amount:220,account:'Compte principal',method:'Carte',reference:'ASS-0912',notes:''}];
const blank={date:new Date().toISOString().slice(0,10),label:'',category:'Autre',type:'Dépense réelle',status:'Payé',amount:0,account:'Compte principal',method:'Carte',reference:'',notes:''};
const money=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'USD'}).format(n);
export function ExpenseManager(){
 const [items,setItems]=useState<Tx[]>(seed);const [selected,setSelected]=useState<Tx|null>(null);const [editing,setEditing]=useState(false);const [draft,setDraft]=useState(blank);const [search,setSearch]=useState('');
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem('finpilot-expenses')||'null');if(x)setItems(x)}catch{}},[]);useEffect(()=>{localStorage.setItem('finpilot-expenses',JSON.stringify(items))},[items]);
 const filtered=useMemo(()=>items.filter(t=>(t.label+' '+t.category+' '+t.reference).toLowerCase().includes(search.toLowerCase())),[items,search]);
 function openNew(){setSelected(null);setDraft(blank);setEditing(true)}
 function openEdit(t:Tx){setSelected(t);setDraft({...t});setEditing(true)}
 function save(e:React.FormEvent){e.preventDefault();if(!draft.label.trim())return;if(selected)setItems(x=>x.map(t=>t.id===selected.id?{id:selected.id,...draft}:t));else setItems(x=>[{id:Date.now(),...draft},...x]);setEditing(false);setSelected(null)}
 return <><div className="topbar"><div><div className="eyebrow">Transactions</div><h1>Dépenses réelles</h1><div className="subtitle">Cliquez sur une dépense pour ouvrir son détail, puis modifiez ou supprimez-la.</div></div><div className="actions"><button className="btn"><Filter size={16}/>Filtrer</button><button className="btn btn-primary" onClick={openNew}><Plus size={16}/>Ajouter</button></div></div>
 <div className="card"><div className="transaction-toolbar"><div className="search-shell transaction-search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher une dépense, catégorie, référence..."/></div><span className="pill">{filtered.length} transaction(s)</span></div><div className="table-wrap"><table className="clickable-table"><thead><tr><th>Date</th><th>Dépense</th><th>Catégorie</th><th>Compte</th><th>Statut</th><th>Montant</th></tr></thead><tbody>{filtered.map(t=><tr key={t.id} onClick={()=>setSelected(t)}><td>{new Date(t.date).toLocaleDateString('fr-FR')}</td><td><strong>{t.label}</strong><div className="cell-sub">{t.type}</div></td><td>{t.category}</td><td>{t.account}</td><td><span className="pill green">{t.status}</span></td><td className="amount negative">-{money(t.amount)}</td></tr>)}</tbody></table></div></div>
 {selected&&!editing&&<div className="drawer-backdrop" onMouseDown={()=>setSelected(null)}><aside className="detail-drawer" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">Détail transaction</div><h2>{selected.label}</h2></div><button className="icon-btn" onClick={()=>setSelected(null)}><X size={17}/></button></div><div className="detail-amount">-{money(selected.amount)}</div><div className="detail-grid"><div><CalendarDays size={16}/><span>Date</span><b>{new Date(selected.date).toLocaleDateString('fr-FR')}</b></div><div><Tag size={16}/><span>Catégorie</span><b>{selected.category}</b></div><div><WalletCards size={16}/><span>Compte</span><b>{selected.account}</b></div><div><span>Méthode</span><b>{selected.method}</b></div><div><span>Référence</span><b>{selected.reference||'—'}</b></div><div><span>Statut</span><b>{selected.status}</b></div></div><div className="detail-notes"><span>Notes</span><p>{selected.notes||'Aucune note.'}</p></div><div className="drawer-actions"><button className="btn btn-primary" onClick={()=>openEdit(selected)}><Pencil size={16}/>Modifier</button><button className="btn" onClick={()=>{setItems(x=>x.filter(t=>t.id!==selected.id));setSelected(null)}}><Trash2 size={16}/>Supprimer</button></div></aside></div>}
 {editing&&<div className="modal-backdrop" onMouseDown={()=>setEditing(false)}><form className="modal-card transaction-form" onMouseDown={e=>e.stopPropagation()} onSubmit={save}><div className="modal-head"><div className="section-title">{selected?'Modifier la dépense':'Ajouter une dépense'}</div><button type="button" className="icon-btn" onClick={()=>setEditing(false)}><X size={17}/></button></div>{[['Libellé','label'],['Catégorie','category'],['Compte','account'],['Méthode de paiement','method'],['Référence','reference']].map(([lab,key])=><div className="field" key={key}><label>{lab}</label><input className="input" value={String(draft[key as keyof typeof draft])} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></div>)}<div className="field"><label>Date</label><input className="input" type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></div><div className="field"><label>Montant</label><input className="input" type="number" value={draft.amount||''} onChange={e=>setDraft({...draft,amount:e.target.value===''?0:Number(e.target.value)})}/></div><div className="field"><label>Statut</label><select className="select" value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option>Payé</option><option>En attente</option><option>Rapproché</option><option>Annulé</option></select></div><div className="field field-wide"><label>Notes</label><textarea className="input textarea" value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></div><div className="recurrence-actions"><button className="btn btn-primary">Enregistrer</button><button type="button" className="btn" onClick={()=>setEditing(false)}>Annuler</button></div></form></div>}
 </>
}
