'use client';
import { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, CalendarDays } from 'lucide-react';

type Event={id:string;date:string;label:string;amount:number;kind:'expense'|'income'|'payable'|'receivable';meta:string};
const money=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export function FinanceCalendar(){
 const [month,setMonth]=useState(()=>new Date().toISOString().slice(0,7)); const [events,setEvents]=useState<Event[]>([]); const [selected,setSelected]=useState<string|null>(null);
 useEffect(()=>{const out:Event[]=[];try{const rules=JSON.parse(localStorage.getItem('finpilot-rules')||'[]');rules.forEach((r:any)=>out.push({id:'r'+r.id,date:r.start,label:r.label,amount:r.amount*r.quantity,kind:'expense',meta:r.frequency}))}catch{}try{const ds=JSON.parse(localStorage.getItem('finpilot-debts')||'[]');ds.forEach((d:any)=>out.push({id:'d'+d.id,date:d.due,label:d.label,amount:Math.max(0,d.amount-d.paid),kind:d.direction,meta:d.counterparty}))}catch{}setEvents(out)},[]);
 const [y,m]=month.split('-').map(Number); const days=new Date(y,m,0).getDate(); const offset=(new Date(y,m-1,1).getDay()+6)%7; const byDay=useMemo(()=>events.filter(e=>e.date.startsWith(month)).reduce<Record<number,Event[]>>((acc,e)=>{const d=Number(e.date.slice(8,10));(acc[d]??=[]).push(e);return acc},{}),[events,month]);
 function shift(n:number){const d=new Date(y,m-1+n,1);setMonth(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`);setSelected(null)}
 const chosen=selected?events.filter(e=>e.date===selected):[];
 return <div className="calendar-layout"><section className="card"><div className="calendar-toolbar"><button className="icon-btn" onClick={()=>shift(-1)}><ChevronLeft size={17}/></button><input className="input month-picker" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><button className="icon-btn" onClick={()=>shift(1)}><ChevronRight size={17}/></button></div><div className="calendar-weekdays">{['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(x=><b key={x}>{x}</b>)}</div><div className="calendar-grid">{Array.from({length:offset}).map((_,i)=><div key={'x'+i} className="calendar-cell muted-cell"/>)}{Array.from({length:days},(_,i)=>i+1).map(d=>{const date=`${month}-${String(d).padStart(2,'0')}`;const es=byDay[d]||[];return <button key={d} className={`calendar-cell ${selected===date?'selected':''}`} onClick={()=>setSelected(date)}><span>{d}</span>{es.slice(0,3).map(e=><i key={e.id} className={`calendar-event ${e.kind}`}>{e.label}</i>)}{es.length>3&&<small>+{es.length-3}</small>}</button>})}</div></section><aside className="card"><div className="section-title"><CalendarDays size={17}/> Détail du jour</div><div className="section-caption">{selected?new Date(selected+'T00:00:00').toLocaleDateString('fr-FR',{dateStyle:'full'}):'Sélectionnez une date du calendrier.'}</div><div className="calendar-agenda">{selected&&chosen.length===0?<div className="empty-cell">Aucune échéance ce jour.</div>:chosen.map(e=><div className="calendar-agenda-item" key={e.id}><div><strong>{e.label}</strong><span>{e.meta}</span></div><b className={e.kind==='income'||e.kind==='receivable'?'positive':'negative'}>{e.kind==='income'||e.kind==='receivable'?'+':'-'}{money(e.amount)}</b></div>)}</div></aside></div>
}
